spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://fungover.org/auth
server:
  port: 8080