spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://your-issuer-uri
          jwk-set-uri: https://your-jwk-set-uri